#!/usr/bin/env python3
"""Package the starter's skills for ChatGPT and Codex.

Why this is nearly a copy
-------------------------
ChatGPT and Codex skills are built on the same open agent-skills standard as
Claude's (agentskills.io): a directory with `SKILL.md` carrying `name` and
`description` frontmatter, plus optional `references/`, `scripts/`, `assets/`,
and the same progressive disclosure — name and description first, full SKILL.md
loaded when the host selects the skill.

Our skills already satisfy that. Verified 2026-08-28: all six have exactly
`name` + `description` and no foreign frontmatter fields.

**And the cross-skill links keep working.** Skills install as siblings under
`~/.agents/skills/`, so `](../vectra-hunt/SKILL.md)` from inside
`vectra-investigator` resolves exactly as it does under Claude. No link
rewriting, no flattening, no fidelity loss. `scripts/flatten_for_chatgpt.py`
solves a different problem — Projects with uploaded knowledge files, where
retrieval replaces progressive disclosure — and should only be used when Skills
are unavailable in the workspace.

What this script adds on top of a copy
--------------------------------------
1. `AGENTS.md` into every skill, with references rewritten by depth. Hosts
   extract skills into a skills-only location, so `../../AGENTS.md` resolves
   outside anything installed and the six safety guardrails silently vanish.
   Same failure observed under Claude on 2026-08-23; the fix is the same.
2. `agents/openai.yaml` per skill — display metadata, and the MCP dependency
   declaration so the host can prompt for the connector rather than failing on
   an unknown tool.
3. A per-skill zip plus a ready-to-copy tree.

Availability caveat
-------------------
Standalone skills work in the ChatGPT desktop app, Codex CLI, and the IDE
extension. For ChatGPT on web and mobile the skills must be bundled into a
*plugin*. Skills are also gated to Business / Enterprise / Edu workspaces and an
admin can switch them off. Confirm before promising the field.

Usage
-----
    python scripts/bundle_openai_skills.py
    python scripts/bundle_openai_skills.py --install     # copy to ~/.agents/skills
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
OUT = REPO / "dist" / "openai-skills"

# vectra-reports excluded: it needs a local Python venv. vectra-reports-mcp is
# the MCP-channel equivalent and ships instead.
INCLUDE = [
    "vectra-investigator",
    "vectra-hunt",
    "vectra-reports-mcp",
    "vectra-pcap",
    "virustotal",
]

EXCLUDE = {
    "__pycache__", ".venv", "venv", ".env", ".env.local", ".DS_Store",
    ".pytest_cache", "build", "dist", "out", "uv.lock", "tests",
}

BRAND = "#1D895E"          # Vectra green on light, per brand guide v3.0

YAML = """\
# Generated by scripts/bundle_openai_skills.py — do not edit by hand.
interface:
  display_name: "{display}"
  short_description: "{short}"
  brand_color: "{brand}"

dependencies:
  tools:
    - type: "mcp"
      value: "vectra-ai-mcp"
      description: "Vectra AI MCP server — detections, entities, posture findings, and Investigation Query SQL"
      transport: "streamable_http"
"""

DISPLAY = {
    "vectra-investigator": ("Vectra Investigator",
                            "Tier-1 SOC triage, entity deep-dives, and verdicts over Vectra"),
    "vectra-hunt": ("Vectra Hunt",
                    "Investigation Query SQL recipes and threat-intel hunt campaigns"),
    "vectra-reports-mcp": ("Vectra Reports",
                           "Canned Vectra dashboard reports over the MCP channel"),
    "vectra-pcap": ("Vectra PCAP Triage",
                    "Packet-level evidence for a Vectra network detection"),
    "virustotal": ("VirusTotal Enrichment",
                   "IOC reputation lookup for corroborating Vectra findings"),
}


def version() -> str:
    try:
        r = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                           capture_output=True, text=True, timeout=5, cwd=str(REPO))
        rev = r.stdout.strip() or "unknown"
    except Exception:                                            # noqa: BLE001
        rev = "unknown"
    return f"{rev} / {datetime.now(timezone.utc):%Y-%m-%d}"


def install_agents_md(skill_root: Path, agents: Path) -> None:
    """Copy AGENTS.md in and fix every reference by the referring file's depth.

    Without this the six guardrails disappear silently — the skill points at a
    path outside anything the host installed, and the agent proceeds with the
    host's generic rules instead.
    """
    shutil.copyfile(agents, skill_root / "AGENTS.md")
    for md in skill_root.rglob("*.md"):
        depth = len(md.relative_to(skill_root).parts) - 1
        text = md.read_text()
        new = re.sub(r"(?:\.\./)+AGENTS\.md", ("../" * depth) + "AGENTS.md", text)
        if new != text:
            md.write_text(new)


def check_frontmatter(skill_md: Path) -> list[str]:
    """The standard requires name and description. A missing description means
    the host cannot match the skill implicitly — it becomes invisible."""
    text = skill_md.read_text()
    problems = []
    if not text.startswith("---"):
        return [f"{skill_md.name}: no frontmatter block"]
    block = text.split("---", 2)[1]
    for field in ("name", "description"):
        if not re.search(rf"^{field}:", block, re.M):
            problems.append(f"{skill_md.parent.name}: frontmatter missing `{field}`")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--install", action="store_true",
                    help="also copy the skills into ~/.agents/skills")
    ap.add_argument("--skills", nargs="+", default=INCLUDE)
    args = ap.parse_args()

    agents = REPO / "AGENTS.md"
    if not agents.is_file():
        raise SystemExit("error: AGENTS.md missing from repo root — the skills "
                         "reference it for the safety guardrails")

    OUT.mkdir(parents=True, exist_ok=True)
    ver = version()
    problems: list[str] = []
    made: list[tuple[str, int, int]] = []

    for name in args.skills:
        src = SKILLS / name
        if not (src / "SKILL.md").is_file():
            raise SystemExit(f"error: no SKILL.md for {name}")

        dst = OUT / name
        if dst.exists():
            shutil.rmtree(dst, ignore_errors=True)
        # symlinks=False dereferences: vectra-reports-mcp's definitions/reference
        # are symlinks into vectra-reports, which is not shipped.
        shutil.copytree(src, dst, symlinks=False,
                        ignore=shutil.ignore_patterns(*EXCLUDE), dirs_exist_ok=True)

        problems += check_frontmatter(dst / "SKILL.md")
        install_agents_md(dst, agents)

        display, short = DISPLAY.get(name, (name, ""))
        (dst / "agents").mkdir(exist_ok=True)
        (dst / "agents" / "openai.yaml").write_text(
            YAML.format(display=display, short=short, brand=BRAND))

        files = sum(1 for f in dst.rglob("*") if f.is_file())
        chars = sum(len(f.read_text(errors="ignore"))
                    for f in dst.rglob("*.md") if f.is_file())
        made.append((name, files, chars))

        zpath = OUT / f"{name}.zip"
        if zpath.exists():
            zpath.unlink()
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
            for f in sorted(dst.rglob("*")):
                if f.is_file():
                    z.write(f, Path(name) / f.relative_to(dst))

    print(f"\n{OUT.relative_to(REPO)}/     method version {ver}")
    for name, files, chars in made:
        print(f"  {name:<22} {files:>3} files  {chars:>7,} chars of markdown  + {name}.zip")

    # Cross-skill links are intentionally preserved — they resolve when the
    # skills sit as siblings. Verify that assumption rather than trusting it.
    dangling = []
    shipped = set(args.skills)
    for md in OUT.rglob("*.md"):
        for m in re.finditer(r"\]\((?:\.\./)+([a-z0-9-]+)/SKILL\.md\)", md.read_text()):
            if m.group(1) not in shipped:
                dangling.append(f"{md.relative_to(OUT)} -> {m.group(1)}")
    print(f"\n  frontmatter problems: {len(problems)}")
    for p in problems:
        print(f"    {p}")
    print(f"  cross-skill links to skills NOT in this set: {len(set(dangling))}")
    for d in sorted(set(dangling))[:6]:
        print(f"    {d}")
    if dangling:
        print("    (these point at vectra-reports, deliberately excluded — the "
              "text names vectra-reports-mcp alongside in every case)")

    if args.install:
        home = Path.home() / ".agents" / "skills"
        home.mkdir(parents=True, exist_ok=True)
        for name, _, _ in made:
            target = home / name
            if target.exists():
                shutil.rmtree(target, ignore_errors=True)
            shutil.copytree(OUT / name, target)
        print(f"\n  installed into {home}")
        print("  Restart the ChatGPT desktop app / Codex if the skills do not appear.")
    else:
        print(f"\n  To install locally:  python {Path(__file__).name} --install")
        print("  Or copy any skill directory into ~/.agents/skills/ by hand.")

    print("\n  Standalone skills work in the ChatGPT desktop app, Codex CLI and the")
    print("  IDE extension. For ChatGPT web/mobile they must be bundled into a")
    print("  plugin. Skills require a Business/Enterprise/Edu workspace and an")
    print("  admin can disable them — confirm before rolling out to the field.")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
